exports.entryTypes = [
  'showcase'
  'style1'
  'style2'
  'style3'
  'style4'
  'style5'
  'style6'
  'style7'
  'special1'
  'special2'
  'special3'
  'special4'
  'special5'
  'cupcakes'
  'child'
  'junior'
  ]

exports.entryNames =
  '2012': 
    showcase: 'Showcakes'
    style1: 'Novelty Single'
    style2: 'Sculpted'
    style3: 'Novelty Tiered'
    style4: 'Wedding Tiered'
    style5: 'Buttercream Single'
    style6: 'Special Techniques'
    style7: 'Confections'
    special1: 'Birthday Tasting'
    special2: 'Cupcakes Tasting'
    special3: 'Renaissance Tasting'
    special4: 'Renaissance Tasting'
    special5: 'Cookies Tasting'
    child: 'Child'
    junior: 'Junior'
  '2013': 
    showcase: 'Showcakes'
    style1: 'Novelty Single'
    style2: 'Sculpted'
    style3: 'Novelty Tiered'
    style4: 'Wedding Tiered'
    style5: 'Buttercream Single'
    style6: 'Special Techniques'
    style7: 'Confections'
    special1: 'Angel Food Tasting'
    special2: 'Mini-Bottle Tasting'
    special3: 'Moon Pies Tasting'
    special4: 'Cookies Tasting'
    special5: 'Candies Tasting'
    child: 'Child'
    junior: 'Junior'

exports.divisions = [
  'adultint'
  'culstudent'
  'adultbeg'
  'professional'
  'junior'
  'adultadv'
  'child'
  'teen'
  'masters'
  ]
  
exports.divisionNames = 
  'adultint': 'Adult Intermediate'
  'culstudent': 'Culinary Student'
  'adultbeg': 'Adult Beginner'
  'professional': 'Professional'
  'junior': 'Junior'
  'adultadv': 'Adult Advanced'
  'child': 'Child'
  'teen': 'Teen'
  'masters': 'Masters'
  